Repository asasine/spongebob, pull requests merged in 2024-10, with the labels that each got.

#19 docs: Added CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation

#23 feat(clipboard)!: removed clipboard support
  Cargo.lock
  Cargo.toml
  README.md
  src/bin/goodboye.rs
  src/main.rs
Labels: enhancement, dependencies

#16 feat: accept text from stdin
  src/lib.rs
  src/main.rs
Labels: enhancement

#27 docs(goodboye): changed about text to something more useful
  src/bin/goodboye.rs
  src/main.rs
Labels: documentation
